swagger: "2.0"
info:
  title: Book-Shelf APIs Docs
  description: This is BookShelf description
  version: 1.0
  contact:
    email: shahalamsharif000@gmail.com
  servers:
    -url: "http://localhost:4000/"
    description: Local server URL
    -url: "https://book-shelf-webapp.herokuapp.com/"
    description: Live server URL

schemes: [http,https]

paths:
  #get all users list
  /all-users:
    get:
      summary: Return array of object with all users
      description: Get all user
      responses:
        200:
          description: Success
  
  #add author
  /add-author:
    post:
      summary: Add book data
      produces: 
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: add author
          schema: 
            type: object
            properties:
              author_name:
                type: string
                required: true
              author_email:
                type: string
                required: false
              photo_url: 
                type: string
                required: true
      responses:
        200:
          description: Success

